settings:
  #username: "Readme-Workflows" # Replace with your username or comment out this line
  commit_msg: "💠 | Update Lorenzo0111/Lorenzo0111 activity"
  max_lines: 10
  url_text: "{REPO}{ID}"
messages:
  comments: "![comment] **Commented:** {URL}"
  issue_opened: "![issueOpened] **Issue opened:** {URL}"
  issue_closed: "![issueClosed] **Issue closed:** {URL}"
  pr_opened: "![prOpened] **Pull request opened:** {URL}"
  pr_closed: "![prClosed] **Pull request closed:** {URL}"
  pr_merged: "![prMerged] **Pull request merged:** {URL}"
  create_repo: "![repoCreated] Created new repository {REPO}"
  fork_repo: "![fork] Forked {FORK} from {REPO}"
  wiki_create: "![wiki] Created new wiki page {WIKI} in {REPO}"
  added_member: "![people] Became collaborator on {REPO}"
  changes_approved: "![approved] Approved {ID} in {REPO}"
  changes_requested: "![changesRequested] Requested changes in {ID} in {REPO}"
  new_release: "![release] Released {ID} in {REPO}"
  new_star: "![star] Starred {REPO}"
